### ISSUE TITLE
MainActivity layout

### ISSUE THREAD

**Issue by gallettilance** [galletti94/main#1]
Get layout from figma - need login, sign up, and browse buttons

**Comment by rhodesrm** [comment]
doing this one now

**Comment by gallettilance** [comment]
@rhodesrm What's the status on this? Do you think we will need to create documentation to guide people in transferring the figma template to android studio?

**Comment by rhodesrm** [comment]
@galletti94 I think that's a good idea, but I have been having trouble directly transferring things from Figma due to the different dimensions of the Figma screens vs Android Studio ones so I've been creating everything in Android Studio from scratch using the Figma screen as a guide.

**Comment by gallettilance** [comment]
@rhodesrm Wonderful! I really appreciate all the work you are doing!
