### ISSUE TITLE
SignUpActivity - signup function

### ISSUE THREAD

**Issue by gallettilance** [galletti94/main#11]
Build a function that signs up a user by calling the various checking functions, the database functions and starts a ViewProfileActivity if valid sign up, otherwise starts LogInActivity with a message or SignUpActivity with a message

**Comment by emampons** [comment]
working on this now

**Comment by emampons** [comment]
Do they sign up then log in, or should they be automatically logged in after they sign up?  Referring to " if valid sign up, otherwise starts LogInActivity with a message or SignUpActivity with a message"

**Comment by gallettilance** [comment]
@Latterization Sorry for the confusion. The intention was that if the user exists in the database he/she should be redirected to the login page. Otherwise log that user in immediately if the signup is valid or go back to the signup activity with an appropriate error message.
