### ISSUE TITLE
ViewTasksActivity Layout

### ISSUE THREAD

**Issue by gallettilance** [galletti94/main#20]
get layout from figma

**Comment by tmoradi** [comment]
I can start on this issue

**Comment by ghost** [comment]
I'll work on this issue

**Comment by gallettilance** [comment]
@tmoradi What's the status on this?

**Comment by ghost** [comment]
@galletti94 I am working on it. The problem is that we did not design a page like this on figma. I will get it done and if it needs to change I can fix those issues as well.

**Comment by gallettilance** [comment]
Sounds good to me but please coordinate with @rhodesrm just in case

**Comment by rhodesrm** [comment]
@tmoradi I think having even a basic outline would be a good idea, we can always add to it/tweak it later! Thank you for your help!

**Comment by gallettilance** [comment]
@tmoradi Any luck with git?
