### ISSUE TITLE
HTTP GET request class

### ISSUE THREAD

**Issue by gallettilance** [galletti94/main#22]
create a class to send get requests to API (can get skeleton from [here](https://github.com/galletti94/blur/tree/master/app/src/main/java/gallettilance/blur))

**Comment by cpchang11** [comment]
Working on this

**Comment by gallettilance** [comment]
@cpchang11 you can now test your get request code with the following url: [https://gai-database.herokuapp.com/](https://gai-database.herokuapp.com/)table

where table = {users, tasks, modules, badges}
