### ISSUE TITLE
LogInActivity - get input text

### ISSUE THREAD

**Issue by gallettilance** [galletti94/main#35]
Write functions (to be called from the onclick listener of the login button) that get the text input from the user and assigns these to variables (to be used in the helper functions of the login activity)

**Comment by emampons** [comment]
started this

**Comment by gallettilance** [comment]
@Latterization What's the status on this? Would be good to have this done for signup too before the weekend so we can focus on the database connection with @cpchang11

**Comment by emampons** [comment]
This one has already been finished and merged, all that needs to be done is to make the API calls

**Comment by gallettilance** [comment]
Excellent - thank you! Let's try to get the signup activity to the same level before the weekend

**Comment by emampons** [comment]
sounds good, I'll handle that @galletti94
