### ISSUE TITLE
Name for the App?

### ISSUE THREAD

**Issue by gallettilance** [galletti94/main#42]
This is an open discussion about the name of the App. If you have any ideas please comment below! If you like names proposed please upvote accordingly

**Comment by Harkish** [comment]
GoBiz

**Comment by Harkish** [comment]
My Business is already an Android App, so delete that one.

**Comment by emampons** [comment]
The current name is nice, "inBusiness"

**Comment by Harkish** [comment]
Hi Lance,

Looking forward to seeing you all next week online.  I was curious, did the folks at Liger ever follow up?  I was really impressed with what they are doing in Cambodia, and would hope they can jump on this collaboration opportunity.

Charlie
